[package]
name = "clipper"
version = "1.0.0"
edition = "2024"
authors = ["ekahPruthvi <ekahpdp@gmail.com>"]
description = "Clipboard manager for cynageOS"
license = "GPL-3.0"

[dependencies]
gtk4 = "0.9.6"
